# This is a basic workflow to help you get started with Actions

name: Workflow to run tox and tests in python

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        python_version:
        - 2.7
        - 3.6
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
